# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigglee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=1500)),
                ('cooking', models.CharField(max_length=15000)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 9, 28, 11, 25, 58, 147316))),
            ],
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
