# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zigglee', '0003_auto_20160928_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking',
            new_name='cooking_method',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='material',
            new_name='ingredients',
        ),
    ]
