# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zigglee', '0005_auto_20160928_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.CharField(default=datetime.datetime(2016, 9, 28, 15, 56, 20, 271538, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_intro',
            field=models.TextField(default=datetime.datetime(2016, 9, 28, 15, 56, 36, 315721, tzinfo=utc), max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_thumb',
            field=models.CharField(default=datetime.datetime(2016, 9, 28, 15, 56, 48, 261676, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=1500),
        ),
    ]
