# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigglee', '0010_recipe_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='visited',
            field=models.BigIntegerField(),
        ),
    ]
