# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigglee', '0012_auto_20160929_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_thumb',
            field=models.ImageField(upload_to=b''),
        ),
    ]
