# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigglee', '0014_auto_20160929_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='visited',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
