# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('stars', models.CharField(max_length=5)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
